### ISSUE TITLE
Nom du fichier SVG

### ISSUE THREAD

**Issue by AlexP20000** [AlexP20000/fablab.web.plandecoupe#10]
Ne pas mettre "thismustbethebest.svg" pour le nom du fichier mais reprendre les dimensions saisies comme suit : **[largeurEnCm]x[longeurEnCm]_[epaisseur]mm-[type].svg**
Avec type = 
- boite,
- outils,
- presentoir

**Comment by Amulus** [comment]
#https://github.com/AlexP20000/fablab.web.plandecoupe/commit/d13e3b67f86d6327b01ca174a4441b88a2aea3c0

**Comment by AlexP20000** [comment]
Supprimer les accolades du nom du fichier

**Comment by AlexP20000** [comment]
Changement de la nomenclature pour un meilleur classement alphabétique des fichiers
