### ISSUE TITLE
Boite avec couvercle à pivot

### ISSUE THREAD

**Issue by AlexP20000** [AlexP20000/fablab.web.plandecoupe#11]
Au sujet de la page pour la boite http://openfactory.univ-brest.fr/decoupes/decoupeBoite_application4_hinged_lid_box.html 

- Changer le titre de page
- Le bouton "télécharger la boite" doit être changé en "Télécharger le plan"
- Mesure interne -> mesure**s** interne**s**

**Comment by Amulus** [comment]
Fait
