### ISSUE TITLE
Boite rectangulaire

### ISSUE THREAD

**Issue by AlexP20000** [AlexP20000/fablab.web.plandecoupe#12]
Sur la page http://openfactory.univ-brest.fr/decoupes/decoupeBoite_application1_opened_closed_box.html
-  Mesure interne -> Mesure**s** interne**s**
- Télécharger la boite ->  Télécharger le plan

**Comment by Amulus** [comment]
#https://github.com/AlexP20000/fablab.web.plandecoupe/commit/d13e3b67f86d6327b01ca174a4441b88a2aea3c0
