### ISSUE TITLE
IHM de saisie

### ISSUE THREAD

**Issue by AlexP20000** [AlexP20000/fablab.web.plandecoupe#5]
Par défaut afficher : 
**Type de planche** : 60 x 80 x 3mm (c'est ce qui est de plus courant)
Il n'existe pas de planche 120x70x1mm -> La supprimer de la liste déroulante
De manière générale, il faudrait améliorer la lisibilité des libellés en ajoutant des espaces entres les chiffres ("60x80x3mm" deviendrait alors : "600 x 800 x 3mm" <- attention à la cohérence des unités ).

**Face(s) de la boîte :** sélectionner "Toutes les faces" par défaut. Si on ouvre la liste déroulante, il faut afficher l'onglet "infos" (attention l’événement n'est pas "onchange").

**Encoches (mm) :** mettre une valeur par défaut (10mm).

**Afficher Planche** : Mettre "Faire apparaître les dimensions de la planche sur le plan de découpe"

**Sauver modèle** : à changer en "Enregistrer les paramètres"

**Charger modèle** : à changer en "restaurer les paramètres"

Bouton **Générer la boite** : à changer en "Prévisualisation". -> Garder le fonctionnement du bouton (disabled, enabled), mais il faut rajouter une prévisualisation automatique lorsqu'on modifie les paramètres (et que la visualisation est possible) pour éviter de devoir cliquer systématiquement sur le bouton une fois qu'on a fait une modification de paramètres.

Rajouter un bouton pour downloader le fichier svg. Il ne faut plus que le download se déclenche sur le bouton "Générer la boite".

**Comment by Siliver4** [comment]
Tout fait, sauf : 
Bouton **Générer la boite ** : à changer en "Prévisualisation". -> Garder le fonctionnement du bouton (disabled, enabled), mais il faut rajouter une prévisualisation automatique lorsqu'on modifie les paramètres (et que la visualisation est possible) pour éviter de devoir cliquer systématiquement sur le bouton une fois qu'on a fait une modification de paramètres.

Rajouter un bouton pour downloader le fichier svg. Il ne faut plus que le download se déclenche sur le bouton "Générer la boite".

**Comment by Siliver4** [comment]
fait à 100% pour la boîte "présentoir", je le ferai aussi pour la première boîte classique la semaine prochaine.

**Comment by Siliver4** [comment]
fait pour toutes les boîtes pour tous les champ y compris les balises select
